<?php

//Fichier de gestion des langues
// Choix de la langue
$Language = 'en';
if(isset($_SERVER['HTTP_ACCEPT_LANGUAGE'])){
  $Langue = explode(",",$_SERVER['HTTP_ACCEPT_LANGUAGE']);
  $Language = strtolower(substr(chop($Langue[0]),0,2)); }
// En fonction de la langue et de la page d'appel remplissage des variables
switch ($Language){
	case 'fr':
	//Français
		$l_monday="lundi"; $l_tuesday="mardi"; $l_wednesday="mercredi"; $l_thursday="jeudi"; $l_friday="vendredi"; $l_saturday="samedi"; $l_sunday="dimanche";
		$l_monthly="mensuelle";$l_weekly="hebdomadaire";$l_daily="journalière";$l_by_session="par session";
		$l_day = "Jour";
	       	$l_limit="limite";
	       	$l_daily_limit="limite journalière";
		$l_used_time = "Temps utilisé";
		$l_last7days_status = "&Eacute;tat sur les 7 derniers jours";
		$l_connections_number = "Nombre de connexions";
		$l_download = "Données téléchargées";
		$l_upload = "Données envoyées";
		$l_average = "moyenne";
		$l_already_exist = "existe d&eacute;j&agrave;";
		$l_search_filter = "Filtre de recherche";
		$l_search_criteria = "Critère de recherche";
		$l_search = "Lancer la recherche";
		$l_no_user_found = "Aucun usager trouvé";
		$l_special_attribute = "Attribut particulier";
		$l_attribute = "Attribut";
		$l_value = "Valeur<br>(vide = tous)";
		$l_user = "Usager";
		$l_users_managment = "Gestion des usagers";
		$l_groups_managment = "Gestion des groupes";
		$l_login = "Identifiant";
		$l_password = "Mot de passe";
		$l_new_password = "Nouveau mot de passe";
		$l_passwd_gen = "générer";
		$l_user_create = "Créer un usager";			
		$l_nb_users = "Nombre d'usagers";			
		$l_group_create = "Créer un groupe";			
		$l_group_select = "Selectionnez un groupe";			
		$l_group = "Groupe";
		$l_created_groups = "Groupe(s) déjà créé(s)";
		$l_group_name = "Nom du groupe";
		$l_group_members = "Membres du groupe :<br>(séparé par un espace ou un 'retour chariot')";
		$l_group_members_remove = "Supprimer tous les membres de ce groupe";
		$l_group_members_to_remove = "<b>Membres à effacer :</b><br>Les membres sélectionnés seront effacés du groupe.<br>Utilisez 'shift' ou 'Ctrl' pour une sélection multiple.";
		$l_group_members_to_add = "<b>Membres à ajouter :</b><br>Separez les membres avec un 'espace' ou un 'retour chariot'.";
		$l_manage_selected_user= "Gérer l'usager sélectionné";
		$l_group_member = "Membre du groupe";
		$l_group_empty = "La liste des groupes est vide";
		$l_main_group = "Le groupe principal est surligné";
		$l_no_open_session = "Aucune session ouverte";
		$l_opened_sessions = "session(s) ouverte(s)";
		$l_active_accounting = "comptabilité(s) active(s)";
		$l_want_to_close ="Voulez-vous les fermer ?";
		$l_yes_close ="Oui, fermer";
		$l_status ="&Eacute;TAT";
		$l_personal_info ="INFORMATIONS PERSONNELLES";
		$l_connections ="CONNEXIONS";
		$l_open_sessions ="SESSIONS OUVERTES";
		$l_members ="MEMBRES";
		$l_attributes ="ATTRIBUTS";
		$l_remove ="SUPPRIMER";
		$l_locked_user ="Le compte usager est verrouillé";
		$l_user_remain_login ="L'usager peut se connecter pendant ";
		$l_user_expired ="Le compte usager a expiré";
		$l_connected ="Connecté depuis";
		$l_connection_time ="Durée de connexion";
		$l_total_connections_time ="Durée cumulée des connexions";
		$l_user_never_login ="Cet usager ne s'est jamais connecté";
		$l_user_not_login_yet ="Cet usager n'est pas connecté actuellement";
		$l_last_login ="Dernière connexion";
		$l_remain_time ="Temps de connexion restant";
		$l_name = "Nom et pr&eacute;nom";
		$l_email = "Adresse de couriel";
		$l_homephone = "Numéro de téléphone privé";
		$l_telephonenumber = "Numéro de téléphone de bureau";
		$l_mobile = "Numéro de téléphone portable";
		$l_lang_ticket = "Langue du ticket";
		$l_simultaneous_use = "Nombre de session simultanée";
		$l_max_all_session = "Période autorisée après la première connexion<br>(en secondes)";
		$l_expiration = "Date d'expiration";
		$l_session_timeout = "Durée maximale d'une session<br>(en secondes)";
		$l_daily_timeout = "Durée de connexion maximale journalière<br>(en secondes)";
		$l_monthly_timeout = "Durée de connexion maximale mensuelle<br>(en secondes)";
		$l_login_time = "Période hebdomadaire";
		$l_max_input_octets = "Maximum de données émises<br>(en octets)";
		$l_max_output_octets = "Maximum de données reçues<br>(en octets)";
		$l_max_total_octets = "Maximum de données échangées<br>(en octets)";
		$l_max_bandwidth_up = "Limite de débit montant<br>(en kbits/seconde)";
		$l_max_bandwidth_down = "Limite de débit descendant<br>(en kbits/seconde)";
		$l_wispr_redirection = "URL de redirection";
		$l_click_for_help = "Cliquez pour afficher l'aide sur cet attribut";	
		$l_show_profile = "Afficher le profil";
		$l_are_you_sure = "&Ecirc;tes-vous sûr de vouloir supprimer";
		$l_yes_remove = "Oui, supprimer";
		$l_create = "Créer";
		$l_change = "Modifier";
		$l_or = "Ou";
		$l_create_multiple = "Créer plusieurs tickets";
		$l_create_multiple_comment = "<br>Remarques : lors de la création plusieurs tickets simultanement :<br>
		- l'identifiant et le mot de passe sont générés aléatoirement,<br>
		- les champs \"Nom, prénom\" et \"Adresse de couriel\" ne sont pas pris en compte.<br> ";
		$l_createTicketsMSG = "Saisissez le nombre d\'utilisateurs à créer";
		$l_spoofing = "Adresse(s) MAC usurpée(s) (Watchdog)";
		$l_virus = "Virus bloqué(s) (HAVP)";
		$l_fail2ban = "Adresse(s) IP bloquée(s) (Fail2Ban)";
	break;
	default :
	//English
		$l_monday="monday"; $l_tuesday="tuesday"; $l_wednesday="wednesday"; $l_thursday="thursday"; $l_friday="friday"; $l_saturday="saturday"; $l_sunday="sunday";
		$l_monthly="monthly";$l_weekly="weekly";$l_daily="daily";$l_by_session="by session";
		$l_day = "Day";
		$l_limit = "limit";
	       	$l_daily_limit="daily limit";
		$l_used_time = "Used time";
		$l_last7days_status = "Last 7 days status";
		$l_already_exist = "already exist";
		$l_connections_number = "Connections number";
		$l_download = "Downloaded data";
		$l_upload = "Uploaded data";
		$l_average = "average";
		$l_user = "User";
		$l_users_managment = "Users managment";
		$l_groups_managment = "Groups managment";
		$l_search_filter = "Search filter";
		$l_search_criteria = "Search criteria";
		$l_search = "Start search";
		$l_no_user_found = "No user found";
		$l_special_attribute = "Special attribute";
		$l_attribute = "Attribute";
		$l_value = "Value<br>(empty = all)";
		$l_login = "Login";
		$l_password = "Password";
		$l_new_password = "New password";
		$l_passwd_gen = "generate";
		$l_user_create = "Create a user";
		$l_nb_users = "Number of users";
		$l_group_create = "Create a group";
		$l_group_select = "Select a group";
		$l_group = "Group";
		$l_created_groups = "Already created group(s)";
		$l_group_name = "Group name";
		$l_group_members = "Members of group :<br>(separate by a 'space' or a 'carriage return')";
		$l_group_members_remove = "Remove all members of this group";
		$l_group_members_to_remove = "<b>Members to remove :</b><br>The selected members will be remove from the group.<br>Use 'shift' or 'Ctrl' for multiple selection.";
		$l_group_members_to_add = "<b>Members to add :</b><br>Separate the members with a 'space' or a 'carriage return'.";
		$l_manage_selected_user= "Manage the selected user";
		$l_group_member = "Member of group";
		$l_group_empty = "The group list is empty";
		$l_main_group = "The main group is highlighted";
		$l_no_open_session = "No open session";
		$l_opened_sessions = "opened session(s)";
		$l_active_accounting = "active accounting(s)";
		$l_want_to_close ="Do you want to close them ?";
		$l_yes_close ="Yes, close";
		$l_status ="STATUS";
		$l_personal_info ="PERSONAL INFORMATIONS";
		$l_connections ="CONNECTIONS";
		$l_open_sessions ="OPEN SESSIONS";
		$l_members ="MEMBERS";
		$l_attributes ="ATTRIBUTES";
		$l_remove ="REMOVE";
		$l_locked_user ="The user account is locked";
		$l_user_remain_login ="The user can log in during ";
		$l_user_expired ="The user account has expired";
		$l_connected ="Connected from";
		$l_connection_time ="Connection time";
		$l_total_connections_time ="Total connections time";
		$l_user_never_login ="This user has never logged in";
		$l_user_not_login_yet ="This user isn't connected yet";
		$l_last_login ="Last connection";
		$l_remain_time ="Remain connection time";
		$l_name = "Surname and name";
		$l_email = "Email Address";	
		$l_homephone = "Personal phone number";
		$l_telephonenumber = "Office phone number";
		$l_mobile = "Mobile phone number";
		$l_lang_ticket = "Voucher language";	
		$l_simultaneous_use = "Number of concurent login";
		$l_max_all_session = "Authorized period after the first connection<br>(in seconds)";
		$l_expiration = "Expiration date";
		$l_session_timeout = "Maximum time for a session<br>(in seconds)";
		$l_daily_timeout = "Maximum time of connection per day<br>(in seconds)";
		$l_monthly_timeout = "Maximum time of connection per month<br>(in seconds)";
		$l_login_time = "Weekly period";
		$l_max_input_octets = "Maximum of data uploaded<br>(in octets)";
		$l_max_output_octets = "Maximum of data downloaded<br>(in octets)";
		$l_max_total_octets = "Maximum of data exchanged<br>(in octets)";
		$l_max_bandwidth_up = "Maximum upload bandwidth<br>(in kbits/second)";
		$l_max_bandwidth_down = "Maximum download bandwidth<br>(in kbits/second)";
		$l_wispr_redirection = "Redirection URL";
		$l_click_for_help = "Click to show help about this attribute";	
		$l_show_profile = "Show profile";
		$l_are_you_sure = "Are you sure to remove";
		$l_yes_remove = "Yes, remove";
		$l_create = "Create";
		$l_change = "Change";
		$l_or = "Or";
		$l_create_multiple = "Create several tickets";
		$l_create_multiple_comment = "<br>Note: when creating multiple tickets simultaneously :<br>
		- username and password are randomly generated,<br>
		- fields \"Surname and name\" and \"Email Address\" are not use.<br> ";
		$l_createTicketsMSG = "Enter the number of users to create";
		$l_spoofing = "MAC address spoofed (Watchdog)";
		$l_virus = "Virus blocked (HAVP)";
		$l_fail2ban = "IP address blocked (Fail2Ban)";
	break;
	}
?>
